<?php

namespace AppBundle\Repository;

/**
 * ActionComptableSocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionComptableSocieteRepository extends \Doctrine\ORM\EntityRepository
{
}
