<?php

namespace AppBundle\Repository;

/**
 * ActionComptableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionComptableRepository extends \Doctrine\ORM\EntityRepository
{
}
