<?php

namespace AppBundle\Repository;

/**
 * AgrementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgrementRepository extends \Doctrine\ORM\EntityRepository
{
}
