<?php

namespace AppBundle\Repository;

/**
 * ApportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApportRepository extends \Doctrine\ORM\EntityRepository
{
}
