<?php

namespace AppBundle\Repository;

/**
 * ApporteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApporteurRepository extends \Doctrine\ORM\EntityRepository
{
}
