<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    const MAX = 20;

    public function cataloguePaginatedAndFiltered($page = 1, $q = ''){
        $qb = $this->createQueryBuilder('a');
        if(strlen($q) > 0){
            $qb->where('a.designation LIKE :q')
                ->setParameter('q', '%'.$q.'%');
        }
        $qb->setMaxResults(self::MAX)
            ->setFirstResult(($page - 1) * self::MAX);

        return new Paginator($qb);
    }
}
