<?php

namespace AppBundle\Repository;

/**
 * ClassificationVenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassificationVenteRepository extends \Doctrine\ORM\EntityRepository
{
}
