<?php

namespace AppBundle\Repository;

/**
 * ClassificationArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassificationArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
