<?php

namespace AppBundle\Repository;

/**
 * ClassificationArticleSocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassificationArticleSocieteRepository extends \Doctrine\ORM\EntityRepository
{
}
