<?php

namespace AppBundle\Repository;

/**
 * ClassificationVenteSocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassificationVenteSocieteRepository extends \Doctrine\ORM\EntityRepository
{
}
