<?php

namespace AppBundle\Repository;

/**
 * CodeInvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeInvitationRepository extends \Doctrine\ORM\EntityRepository
{
}
