<?php

namespace AppBundle\Repository;

/**
 * CompteComptableSocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteComptableSocieteRepository extends \Doctrine\ORM\EntityRepository
{
}
