<?php

namespace AppBundle\Repository;

/**
 * CompteComptableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteComptableRepository extends \Doctrine\ORM\EntityRepository
{
}
