<?php

namespace AppBundle\Repository;

/**
 * CompteComptableParActionComptableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteComptableParActionComptableRepository extends \Doctrine\ORM\EntityRepository
{
}
