<?php

namespace AppBundle\Repository;

/**
 * ConditionsDeReglementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionsDeReglementsRepository extends \Doctrine\ORM\EntityRepository
{
}
