<?php

namespace AppBundle\Repository;

/**
 * CoordonneesBanqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordonneesBanqueRepository extends \Doctrine\ORM\EntityRepository
{
}
