<?php

namespace AppBundle\Repository;

/**
 * FormeJuridiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormeJuridiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
