<?php

namespace AppBundle\Repository;

/**
 * InformationAdministrativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationAdministrativeRepository extends \Doctrine\ORM\EntityRepository
{
}
