<?php

namespace AppBundle\Repository;

/**
 * LigneDepenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneDepenseRepository extends \Doctrine\ORM\EntityRepository
{
}
