<?php

namespace AppBundle\Repository;

/**
 * MargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MargeRepository extends \Doctrine\ORM\EntityRepository
{
}
