<?php

namespace AppBundle\Repository;

/**
 * ModeDePaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeDePaiementRepository extends \Doctrine\ORM\EntityRepository
{
}
