<?php

namespace AppBundle\Repository;

/**
 * NatureArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NatureArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
