<?php

namespace AppBundle\Repository;

/**
 * OperationSurCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationSurCompteRepository extends \Doctrine\ORM\EntityRepository
{
}
