<?php

namespace AppBundle\Repository;

/**
 * SecteurActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecteurActiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
