<?php

namespace AppBundle\Repository;

/**
 * SystemeComptableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemeComptableRepository extends \Doctrine\ORM\EntityRepository
{
}
