<?php

namespace AppBundle\Repository;

/**
 * TypeDeDocumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDeDocumentsRepository extends \Doctrine\ORM\EntityRepository
{
}
