<?php

namespace AppBundle\Repository;

/**
 * UtilisateurSocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurSocieteRepository extends \Doctrine\ORM\EntityRepository
{
}
