# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fosUsers:
            id: fos_user.user_provider.username_email

    encoders:
        Dup\UserBundle\Entity\User: sha512

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        app:
            pattern: ^/
            anonymous: true
            provider:  fosUsers
            form_login:
                login_path: fos_user_security_login
                check_path: /login-check
                default_target_path: index
            oauth:
                resource_owners:
                    facebook:           "/connect/check-facebook"
                    google:           "/connect/check-google"
                login_path:        /login
                failure_path:      /login
                oauth_user_provider:
                    service: my.oauth_aware.user_provider.service
            logout:
                path:   dup_user_logout
                target: /login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login-check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/social-registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }